### ISSUE TITLE
Issue when searching with blank search query.

### ISSUE THREAD

**Issue by paulio84** [paulio84/MovieSearch#3]
There is an error when searching with a blank search query.

![image](https://user-images.githubusercontent.com/22069939/69787348-40f7f980-11b4-11ea-99c4-5edd818a9d9b.png)

This needs to be handled correctly.

**Comment by stainless-crab** [comment]
Please assign to me.

**Comment by stainless-crab** [comment]
A simple fix here is too add the required attribute to the input field.

Or we could do more and add something custom.

**Comment by paulio84** [comment]
I'd like to see something custom.
